---
name: "Anime"
guid: "a4df60c5-6ab4-412a-8f79-2cab93fb2bc5"
version: "11.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "jellyfin"
overview: "Manage your anime from Jellyfin"
description: >
  Manage your anime in Jellyfin. This plugin supports several different metadata providers
  and options for organizing your collection.
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.AniSearch.dll"
changelog: >
  changelog
