name: "AniSearch"
guid: "776d9158-b91f-49d9-82c5-dacce63d63b8"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-anisearch.png"
version: "3"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "jellyfin"
overview: "AniSearch metadata provider"
description: >
  AniSearch metadata provider

category: "Metadata"
artifacts:
  - "Jellyfin.Plugin.AniSearch.dll"
changelog: |2-
  ### Dependency updates ###
  - chore(deps): bump release-drafter/release-drafter from v5.14.0 to v5.15.0 (#3) @dependabot

  ### CI & build changes ###
  - Update ci (#5) @h1dden-da3m0n
  - Let there be CI (#2) @oddstr13

  ### Code or Repo Maintenance ###
  - chore: plugin images (#4) @h1dden-da3m0n
