---
name: "AniSearch"
guid: "776d9158-b91f-49d9-82c5-dacce63d63b8"
version: "2.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "jellyfin"
overview: "AniSearch metadata provider"
description: >
  AniSearch metadata provider
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.AniSearch.dll"
changelog: >
  - Split out from the Anime plugin
  - Remove dependency on DependencyInjection
